### ISSUE TITLE
prebuilt artifacts

### ISSUE THREAD

**Issue by sroussey** [websockets/bufferutil#154]
I found this project to be a good example of how to do pre-built binaries for a node project. I am helping another project do this and while working on it I noticed some things that apparently don't affect you (yet) but may in the future.

Specifically, when you upload artifacts in the latest version, it does not let you reuse the name. This impacts `windows-latest` which you currently have both the i32 and x64 inside. I think it is v4 that disallows this.

I fixed this by adding the arch to the name

```yml
    - uses: actions/upload-artifact@v4
       with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: prebuilds
          retention-days: 1
```

You will want to account for that change where you `tar` things up as well.
